# Generated by Django 4.2.7 on 2023-12-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecontractstatus',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='employeecontractstatus',
            name='employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='date_applied',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='EmployeeContractStatus',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
