# Generated by Django 4.2.7 on 2023-12-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_organizer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
