# Generated by Django 4.2.7 on 2023-12-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_delete_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ManyToManyField(related_name='employees', to='webapp.group'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_picture/'),
        ),
    ]
